services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - static_data:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env   # Load env vars for Django

  db:
    image: postgres:15
    env_file:
      - .env   # Load env vars for Postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  static_data: