name: Postgres Test

on:
  push:
    branches: [ "master" ]

jobs:
  db-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U testuser"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Check Postgres is running
        run: |
          sudo apt-get update && sudo apt-get install -y postgresql-client
          PGPASSWORD=testpass psql -h localhost -U testuser -d testdb -c "SELECT 1;"
